### PR TITLE
[Rev 1 Docs] Migrate to Camel Case

### LINKED ISSUE #671: [Rev 1 Docs] Code Implementation - Standardize on Camel Case
Camel and snake case are used throughout the code base. Camel case has been chosen as the standard that we will follow.

### PR DESCRIPTION
**Pull request by arkinmodi**
Ran this `sed` expression and then manually fixed things.

```bash
sed -Ei 's/_([a-z])/\U\1/gi;s/^([A-Z])/\l\1/' ...
```

Close https://github.com/arkinmodi/project-sayyara/issues/671

### CODE REVIEW

**Comment by joyxiao99** [comment]
can you try to create a quote and then click on the quote chat, for some reason it didn't work for me. Seems to work on prod tho

image

**Comment by TimChoy** [comment]
> can you try to create a quote and then click on the quote chat, for some reason it didn't work for me. Seems to work on prod tho
> 
> image

Can you explain how this happened? I can't recreate it.

**Comment by arkinmodi** [comment]
> can you try to create a quote and then click on the quote chat, for some reason it didn't work for me. Seems to work on prod tho
> 
> 
> 
> image
> 
> 

I've encountered this bug randomly for the past month, so I don't think it is related to this PR.

Edit: I have been able to replicate this on the main branch. If you go slowly it won't happen. From what I have seen there are 3 phases the `quotes` array goes through:

```javascript
1 {clfcmff1s0001s4ywml3atx04: {…}, clfcmeq6v0000s4ywfnv5c12n: {…}}
2 {clfcmff1s0001s4ywml3atx04: {…}, clfcmeq6v0000s4ywfnv5c12n: {…}, undefined: {…}}
3 {clfcn2gn00003s4ywmmx4pjl7: {…}, clfcmff1s0001s4ywml3atx04: {…}, clfcmeq6v0000s4ywfnv5c12n: {…}}
```

If you go slow, you let it settle on the third and correct phase. It shows up in different ways. Sometimes, the new chat won't be on the left nav and pops in later. Sometimes the new chat is on the left nav and clicking it causes the error seen above.

**Comment by joyxiao99** [comment]
> > can you try to create a quote and then click on the quote chat, for some reason it didn't work for me. Seems to work on prod tho
> > image
> 
> I've encountered this bug randomly for the past month, so I don't think it is related to this PR.
> 
> Edit: I have been able to replicate this on the main branch. If you go slowly it won't happen. From what I have seen there are 3 phases the `quotes` array goes through:
> 
> ```js
> 1 {clfcmff1s0001s4ywml3atx04: {…}, clfcmeq6v0000s4ywfnv5c12n: {…}}
> 2 {clfcmff1s0001s4ywml3atx04: {…}, clfcmeq6v0000s4ywfnv5c12n: {…}, undefined: {…}}
> 3 {clfcn2gn00003s4ywmmx4pjl7: {…}, clfcmff1s0001s4ywml3atx04: {…}, clfcmeq6v0000s4ywfnv5c12n: {…}}
> ```
> 
> If you go slow, you let it settle on the third and correct phase. It shows up in different ways. Sometimes, the new chat won't be on the left nav and pops in later. Sometimes the new chat is on the left nav and clicking it causes the error seen above.

yikes ok. I tested out the other things so I guess we can merge

**Review by joyxiao99 — APPROVED** [review]

**Review by TimChoy — APPROVED** [review]

**Pull request merged**
